#!/usr/bin/env node
const prog = require('caporal');
const ora = require('ora');
const exec = require('child_process').exec;
const util = require('./command/common/util');
const { getInstalledPath } = require('get-installed-path');
const inquirer = require('inquirer');
const opener = require("opener");

//commands
const projectInit  = require('./command/project-init');
const projectBuild = require('./command/project-build');

prog
  .version('1.0.0')
  .command('init',   'Crie um novo projeto')
  .argument('[artifactId]', 'Nome do artefato', /^[a-zA-Z0-9]+$/g)
  .argument('[groupId]', 'Nome do grupo')
  .argument('[version]', 'Versão do projeto')
  .action((args, options, logger) => projectInit.run(args, options, logger))
  .command('build',   'Faz a compilação dos módulos')
  .action((args, options, logger) => projectBuild.run(args, options, logger))

getInstalledPath('@angular/cli').then(function(pt){
  //First Verify Java
  util.testApplicationInstalled('java', 'java version', function(javaInstalled){
    if(javaInstalled){
      util.testApplicationInstalled('mvn', 'Apache Maven', function(mavenInstalled){
        if(mavenInstalled){
          prog.parse(process.argv);
        }else{
          inquirer.prompt([
              {
                  type: 'confirm',
                  name: 'openMaven',
                  message: `Não encontramos o MAVEN na sua maquinha, deseja saber informações de como instala-lo?`
              }
          ]).then(answersMaven => {
            if(answersMaven.openMaven){
              opener('https://maven.apache.org/download.cgi');
            }else{
              console.log('Finalize a instalação das dependências e tente novamente.');
            }
          })
        }
      });
    }else{
      inquirer.prompt([
          {
              type: 'confirm',
              name: 'openJava',
              message: `Não encontramos o JAVA na sua maquinha, deseja saber informações de como instala-lo?`
          }
      ]).then(answersJava => {
        if(answersJava.openJava){
          opener('http://www.oracle.com/technetwork/pt/java/javase/downloads/jdk8-downloads-2133151.html');
        }else{
          console.log('Finalize a instalação das dependências e tente novamente.');
        }
      })
    }
  });
}, () => {
  //pede para o usuário instalar o angular cli.
  const spinner = ora('Aguarde...').start();
  spinner.fail(`Não encontramos algumas dependências, execute: npm install -g @angular/cli`);
});
